---
beta-diversity
---

This script requires files generated by the following scripts:
OTU_filtering.RMD 
vsd_normalization.RMD

Load libraries
```{r}
library(dplyr)
library(tidyr)
library(ggplot2)
library(phyloseq)
library(ape)
library(vegan)
library(broom)
library(gridExtra)
library(grid)
library(RColorBrewer)
```

Load data and reformat
```{r}
otu <- readRDS("../Data/otu_vsd_blind.RDS")
otu[otu < 0.0] <- 0.0

map <- readRDS("../Data/map.RDS")
tree <- read_tree("../Data/rep_set.tre")

map$Compartment <- factor(map$Compartment,
                          levels = c("BS","RS","ES"),
                          labels = c("Bulk Soil", "Rhizosphere", "Endosphere"))
map$Soil <- factor(map$Soil,
                   levels = c("A","B","D"),
                   labels = c("Arbuckle", "Biggs", "Davis"))
map$Treatment <- factor(map$Treatment,
                        levels = c("WC", "DS"),
                        labels = c("Control", "Drought"))
map$Cultivar <- factor(map$Cultivar,
                       levels = c("G1", "G2", "S1", "S2"))

map.nbs <- filter(map, Compartment != "Bulk Soil")

physeq <- phyloseq(otu_table(otu, taxa_are_rows = TRUE), tree)

dist <- as.matrix(phyloseq::distance(physeq, method = "wunifrac"))
dist <- dist[match(map$SampleID, rownames(dist)), match(map$SampleID, colnames(dist))]

```

Perform PCoA
```{r}

pcoa <- pcoa(as.dist(dist))
axes <- as.data.frame(pcoa$vectors)
axes$SampleID <- rownames(axes)
axes <- merge(map, axes, by.x = "SampleID", by.y = "SampleID")

eigval <- round(pcoa$values$Relative_eig * 100, digits = 2)
eigval <- data.frame( PC = 1:length(eigval), Eigval = eigval)
```

Plot
```{r}

p <- ggplot(axes, aes(Axis.1, Axis.2)) 

a <- p + geom_point(aes(colour = Soil), size = 3,alpha=0.8) +
  xlab(paste("PCo1 (", eigval$Eigval[1], " %)", sep = "")) +
  ylab(paste("PCo2 (", eigval$Eigval[2], " %)", sep = "")) +
  scale_color_manual(values = c("#E78AC3", "#A6D854", "#FFD92F")) +
  geom_vline(xintercept = 0, linetype = 2) +
  geom_hline(yintercept = 0, linetype = 2) +
  theme_bw() +
  theme(text = element_text(size = 18),
        legend.position = "bottom") +
  guides(colour = guide_legend(title.position = "top", title.hjust = 0.5)) 

p <- ggplot(axes, aes(Axis.1, Axis.2)) 

b <- p + geom_point(aes(colour = Compartment), size = 3,alpha=0.8) +
  xlab(paste("PCo1 (", eigval$Eigval[1], " %)", sep = "")) +
  ylab(paste("PCo2 (", eigval$Eigval[2], " %)", sep = "")) +
  scale_color_manual(values = c("#BC80BD", "#FB8072", "#80B1D3")) +
  geom_vline(xintercept = 0, linetype = 2) +
  geom_hline(yintercept = 0, linetype = 2) +
  theme_bw() +
  theme(text = element_text(size = 18),
        legend.position = "bottom") +
  guides(colour = guide_legend(title.position = "top", title.hjust = 0.5)) 

p <- ggplot(axes, aes(Axis.1, Axis.3)) 

c <- p + geom_point(aes(colour = Treatment), size = 3,alpha=0.8) +
  xlab(paste("PCo1 (", eigval$Eigval[1], " %)", sep = "")) +
  ylab(paste("PCo3 (", eigval$Eigval[3], " %)", sep = "")) +
  scale_color_manual(values = c("#5AB4AC", "#D8B365" )) +
  geom_vline(xintercept = 0, linetype = 2) +
  geom_hline(yintercept = 0, linetype = 2) +
  theme_bw() +
  theme(text = element_text(size = 18),
        legend.position = "bottom") +
  guides(colour = guide_legend(title.position = "top", title.hjust = 0.5)) 

a;b;c
```

Run PERMANOVA
```{r}
pmanova <- adonis(as.dist(dist) ~ Compartment + Soil + Treatment + Compartment:Treatment + Soil:Treatment + Library,  data = map)

map.nbs <- filter(map, Compartment != "Bulk Soil")
dist.nbs <- dist[match(map.nbs$SampleID, rownames(dist)), match(map.nbs$SampleID, colnames(dist))]
pmanova.nbs <- adonis(as.dist(dist.nbs) ~ Compartment + Soil + Treatment + Cultivar + Compartment:Treatment + Soil:Treatment + Cultivar:Treatment + Library,  data = map.nbs)

pmanova;pmanova.nbs
```


Perform CAP to test cultivar effect
```{r}
cap.clt <- capscale(as.dist(dist.nbs) ~ Cultivar + Condition(Compartment + Soil + Treatment + Library), data = map.nbs, add = T, na.action = na.omit)
cap.axes <- as.data.frame(scores(cap.clt, choices = c(1,2,3,4))$sites)
cap.axes$SampleID <- rownames(cap.axes)
cap.clt.axes <- inner_join(cap.axes, map, by = "SampleID")
cap.clt.eigval <- round(cap.clt$CCA$eig/sum(cap.clt$CCA$eig) * 100, digits = 2)
cap.clt.eigval <- data.frame(PC = 1:length(cap.clt.eigval), Eigval = cap.clt.eigval)


cap.clt.anova <- anova(cap.clt, by = "terms")

p <- ggplot(cap.clt.axes, aes(CAP1, CAP2))
d <- p + geom_point(aes(colour = Cultivar), size = 3,alpha=0.8) +
  scale_color_manual(values = c(brewer.pal(12, "Paired")[c(7:10)])) +
  labs(x = paste("CAP1 (", cap.clt.eigval$Eigval[1], " %)", sep = ""),
       y = paste("CAP2 (", cap.clt.eigval$Eigval[2], " %)", sep = "")) +
  geom_vline(xintercept = 0, linetype = 2) +
  geom_hline(yintercept = 0, linetype = 2) +
  theme_bw() +
  theme(text = element_text(size = 18),
        legend.position = "bottom") +
  guides(colour = guide_legend(title.position = "top", title.hjust = 0.5)) 

d
```

Perform CAP to test the compartment x treatment interaction
```{r}
cap.cmp <- capscale(as.dist(dist)~ Compartment * Treatment + Condition(Soil + Library), data = map, add = T, na.action = na.omit)
cap.axes <- as.data.frame(scores(cap.cmp, choices = c(1,2,3,4))$sites)
cap.axes$SampleID <- rownames(cap.axes)
cap.cmp.axes <- inner_join(cap.axes, map, by = "SampleID")
cap.cmp.eigval <- round(cap.cmp$CCA$eig/sum(cap.cmp$CCA$eig) * 100, digits = 2)
cap.cmp.eigval <- data.frame(PC = 1:length(cap.cmp.eigval), Eigval = cap.cmp.eigval)


cap.cmp.anova <- anova(cap.cmp, by = "terms")

p <- ggplot(cap.cmp.axes, aes(CAP1, CAP2))
e <- p + geom_point(aes(colour = Compartment, shape = Treatment), size = 3,alpha=0.8) +
  scale_color_manual(values = c("#BEBADA", "#FB8072", "#80B1D3")) +
  labs(x = paste("CAP1 (", cap.cmp.eigval$Eigval[1], " %)", sep = ""),
       y = paste("CAP2 (", cap.cmp.eigval$Eigval[2], " %)", sep = "")) +
  geom_vline(xintercept = 0, linetype = 2) +
  geom_hline(yintercept = 0, linetype = 2) +
  theme_bw() + 
  theme(text = element_text(size = 18)) 
e
```

Run simple effects analysis
I follow the example shown in:
http://thebiobucket.blogspot.com/2011/08/two-way-permanova-adonis-with-custom.html#more
```{r}

treatment <- map$Treatment 

contrasts(treatment) <- c(-1, 1)
Trt <- model.matrix(~ treatment)[, -1]

## create a design matrix of the contrasts for "treatment"

trt.in.bs <- Trt * ifelse(map$Compartment == "Bulk Soil", 1, 0)
trt.in.rs <- Trt * ifelse(map$Compartment == "Rhizosphere", 1, 0)
trt.in.es <- Trt * ifelse(map$Compartment == "Endosphere", 1, 0)

test.map <- map

test.map$treatment <- treatment

test.map$trt.in.bs <- trt.in.bs
test.map$trt.in.rs <- trt.in.rs
test.map$trt.in.es <- trt.in.es

trt.in.cmp <- adonis(dist ~ Compartment + Soil  + trt.in.bs + trt.in.rs + trt.in.es, data = test.map)
trt.in.cmp
```
